### ISSUE TITLE
What license will guide Lasr source use and development activity?

### ISSUE THREAD

**Issue by dcslagel** [donald-keighley/lasr#1]
What license will guide Lasr source use and development activity?

Thanks,
DC

**Comment by donald-keighley** [comment]
Good question.  I don't really know much about licenses, but I also don't care much who uses it or what they do with it.  What would you suggest?

**Comment by dcslagel** [comment]
Okay, it sounds like a basic open-source approach.  There are several license option.  These two are probably sensible options...

I often adopt the license of the programming language. It looks like R-lang uses GNU GENERAL PUBLIC LICENSE Version 2, June 1991 : 
https://www.r-project.org/COPYING.  
So that would be work for what you described above.  It is a copy-left license, which does have additional rules.  Here is a nice overview: 
https://choosealicense.com/licenses/gpl-2.0/   

Also the MIT is simpler in language and even less requirements that GNU v2.  This is what Lasio uses.
MIT:
https://choosealicense.com/licenses/mit/

DC

**Comment by donald-keighley** [comment]
Will look into it, thanks.

**Comment by donald-keighley** [comment]
So, does the fact that my package depends on the data.table package make any difference?  Looks like it uses MPL-2.

**Comment by donald-keighley** [comment]
I changed the license to MPL-2.  I chose that because I have two dependencies right now, data.table and Rcpp.  Rcpp and R itself use GPL-2 and therefore require a GPL compatible license.  data.table use MPL-2 and Matt Dowle's reason for doing so can be read here:

https://github.com/Rdatatable/data.table/pull/2456

Specifically, this quote is what I'm shooting for:

"The MPL (Mozilla Public License) does not have those restrictions. The MPL is even lesser than the LGPL. It is the lowest we can go with throwing the code to the wind and going with a lax license like MIT or Apache which would allow closed-source data.table.PRO to be created."

Hopefully that works.  Thanks for bringing this up.
